### ISSUE TITLE
Add support to customize the shipment status

### ISSUE THREAD

**Issue by laundy** [vendidero/woocommerce-germanized-shipments#8]
Hey folks,

first of all - Germanized is an amazing plugin!

One improvement I'd like to suggest though: You are not considering the type of order when displaying the shipment status in `Orders`.
A customer of mine offers `Click & Collect` and all order shipment status are automatically in `Shipped` state. However, I would propose to have access to the `$order` or the `$order_shipment` to change the shipment status based on the shipment type using the already existing filter `woocommerce_gzd_order_shipping_status_name`. This seems to not be possibel at the moment.

This is the relevant code for displaying the status:
https://github.com/vendidero/woocommerce-germanized-shipments/blob/e0c7960f152e0d3a6f85dea7d077cda76f51212f/includes/wc-gzd-shipment-functions.php#L257-L281

Passing the `$order_shipment` or at least the result of `$order_shipment->needs_shipping()` to the filter call might solve it already:
https://github.com/vendidero/woocommerce-germanized-shipments/blob/c57ee9672df6895abb9be6cd312937e80a1bf962/includes/admin/views/html-order-shipments.php#L20

Please let me know what you think about it.

Thanks,

Johannes

**Comment by dennisnissle** [comment]
Hi there,

sorry for coming back so late. I've added the `woocommerce_gzd_shipment_order_shipping_status` filter which you might use to adjust the actual shipping status of the order (based on certain conditions). You might furthermore use the `woocommerce_gzd_order_shipping_statuses` filter to register an additional status.

Cheers
