### ISSUE TITLE
Add possibility to check DHL credentials

### ISSUE THREAD

**Issue by laundy** [vendidero/woocommerce-germanized-shipments#9]
Hello vendidero team,

as you know, there is no option to check if the credentials for the DHL integration are correct and are working fine.
I consider such a functionality as crucial as these need to be changed regularly which introduces error possibilities.

What do you think about adding a `Check Credentials` button in the `API` section of the DHL integration settings that triggers an authentication request that can either succeed or fail?

Regards,

Johannes

**Comment by dennisnissle** [comment]
Hi Johannes,

I've just added the connection status check to the API settings page: https://github.com/vendidero/woocommerce-germanized-dhl/commit/b68929af119927368703ed43ee20f24ec91ee4b6

Unfortunately the DHL API does not support a built-in way to test the credentials.

Cheers
